/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import classes.*;
import java.io.FileInputStream;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author isaacmsl
 */
public class TelaListar extends javax.swing.JFrame {

    /**
     * Creates new form TelaCriar
     */
    
    private ArrayList<Tabela> tabelas;
    private ArrayList<Tabela> tabelasSelected;
    private boolean listouTabelas;
    
    public TelaListar() {
        initComponents();
        
        tabelas = new ArrayList<>();
       
        try {
            ArrayList<Tabela> tabelasImutavel = ManipuladorIOFiles.lerArquivoTabela("tabelas.dat");
            this.tabelas = tabelasImutavel;
            tabelasSelected = new ArrayList<Tabela>();
        
            listarTabelas();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi possível ler o arquivo!");
            this.dispose();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        btnVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        txtInfo = new javax.swing.JLabel();
        btnVer = new javax.swing.JButton();
        btnAddLinha = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        panel.setBackground(new java.awt.Color(255, 255, 255));

        btnVoltar.setBackground(new java.awt.Color(255, 255, 255));
        btnVoltar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(list);

        txtInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtInfo.setText("Selecione uma tabela abaixo:");

        btnVer.setBackground(new java.awt.Color(255, 255, 255));
        btnVer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVer.setText("Ver");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });

        btnAddLinha.setBackground(new java.awt.Color(255, 255, 255));
        btnAddLinha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddLinha.setText("AddLinha");
        btnAddLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLinhaActionPerformed(evt);
            }
        });

        btnRemover.setBackground(new java.awt.Color(255, 255, 255));
        btnRemover.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(btnAddLinha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRemover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVoltar)
                .addGap(28, 28, 28))
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtInfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(txtInfo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnVer)
                    .addComponent(btnAddLinha)
                    .addComponent(btnRemover))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        
        this.dispose();
        
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        
        if(list.isSelectionEmpty()){ 
            JOptionPane.showMessageDialog(null, "Selecione uma tabela!");
        }
        else {
            
            setTabelasSelected();
            
            listouTabelas = true; // usar para nao encher os tabelasSelected
            
            for (Tabela tabela : tabelasSelected) {
                new TelaInfoTabela(tabela).setVisible(true);
            }
            
        }
        
    }//GEN-LAST:event_btnVerActionPerformed

    private void btnAddLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLinhaActionPerformed
        if (list.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecione uma tabela!");
        } else {
            setTabelasSelected();
            
            listouTabelas = true; // usar para nao encher os tabelasSelected
            
            for (Tabela tabela : tabelasSelected) {
                new TelaLinha(tabela).setVisible(true);
            }
            
        }
    }//GEN-LAST:event_btnAddLinhaActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        if (list.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecione uma tabela!");
        } else {
            int resposta = JOptionPane.showConfirmDialog( null,"Confirma remoção da(s) tabela(s)?", "Remoção",JOptionPane.YES_NO_OPTION);
            
            setTabelasSelected();
            
            listouTabelas = true; // usar para nao encher os tabelasSelected
            
            if (resposta == 0) { // SIM
                removerTabelas();
            }
        }
    }//GEN-LAST:event_btnRemoverActionPerformed
    
    private void removerTabelas() {
    
        try {
            ArrayList<Tabela> tabelasExistentes = ManipuladorIOFiles.lerArquivoTabela("tabelas.dat");
        
            try {
                
                for (Tabela tabela: tabelasSelected) {
                    tabelasExistentes.remove(tabela);
                }
            
                ManipuladorIOFiles.gravarArquivo("tabelas.dat", tabelasExistentes, false);
                
                JOptionPane.showMessageDialog(null, "Tabela(s) removida(s) com sucesso!");
                
                this.tabelas = tabelasExistentes;
                
                listarTabelas();
                
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao tentar remover a tabela.");
            }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível ler o arquivo");
        }
        
        
        
    }
    
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaListar().setVisible(true);
            }
        });
    }
    
    private void listarTabelas() {
        list.setModel(new javax.swing.AbstractListModel<String>() {

            public int getSize() {
                return tabelas.size();
            }

            public String getElementAt(int i) {
                return tabelas.get(i).getNome();
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddLinha;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnVer;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel txtInfo;
    // End of variables declaration//GEN-END:variables

    private void setTabelasSelected() {
        
        if(listouTabelas) {
            tabelasSelected.clear();
            listouTabelas = false;
        }
        
        for (Tabela tabela : tabelas) {
            
            for (String selected : list.getSelectedValuesList()) {
                
                if (tabela.getNome().equalsIgnoreCase(selected)) {
                    tabelasSelected.add(tabela);
                }
            }
        }   
        
    }


}
